const colors = {
  light: {
    text: "#0a0a0a",
    tint: "#6C47FF",
    background: "#F5F5FA",
    foreground: "#0a0a0a",
    card: "#ffffff",
    cardForeground: "#0a0a0a",
    primary: "#6C47FF",
    primaryForeground: "#ffffff",
    secondary: "#f0f0f5",
    secondaryForeground: "#1a1a1a",
    muted: "#f0f0f5",
    mutedForeground: "#737373",
    accent: "#ededfa",
    accentForeground: "#1a1a1a",
    destructive: "#FF4444",
    destructiveForeground: "#ffffff",
    border: "#e0e0ee",
    input: "#e8e8f0",
    success: "#00C896",
    warning: "#FF9500",
    surface: "#e8e8f0",
    surfaceForeground: "#555577",
  },
  dark: {
    text: "#F0F0FF",
    tint: "#8B6FFF",
    background: "#0A0A12",
    foreground: "#F0F0FF",
    card: "#12121E",
    cardForeground: "#F0F0FF",
    primary: "#7C5CFF",
    primaryForeground: "#ffffff",
    secondary: "#1C1C2E",
    secondaryForeground: "#F0F0FF",
    muted: "#1C1C2E",
    mutedForeground: "#8A8AAE",
    accent: "#252538",
    accentForeground: "#F0F0FF",
    destructive: "#FF5555",
    destructiveForeground: "#ffffff",
    border: "#252538",
    input: "#1C1C2E",
    success: "#00D395",
    warning: "#FF9500",
    surface: "#1C1C2E",
    surfaceForeground: "#AAAABF",
  },
  radius: 16,
};

export default colors;
